#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
evaluate_user_reconstruction.py
===============================

Per-user "did we actually reconstruct THIS user?" fidelity check.

Phase 2c of the pipeline produces a forum where every post is generated by
the hypernetwork-conditioned model on a real user's g-vector. This script compares
each user's generated posts against that user's actual training-corpus posts
along three axes:

  1. Style embedding cosine similarity:
       sentence-transformer mean embedding of generated posts vs training posts
  2. GoEmotions polarity MAE:
       per-user sentiment of generated text vs per-user sentiment of training
  3. Lexical overlap:
       Jaccard over normalized unigrams (sanity check; not a primary metric)

Outputs (under --out_dir)
-------------------------
  per_user_reconstruction.csv      one row per user with all 3 metrics
  reconstruction_summary.json      cohort + global aggregates with bootstrap CIs
  reconstruction_plot.png          scatter of style cosine vs sentiment MAE

The script is intentionally self-contained: it only reads forum.parquet,
the training-corpus parquet, and the GoEmo user labels CSV. No engine load.
"""
from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

LOG = logging.getLogger("recon")
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)-8s %(message)s",
                    datefmt="%Y-%m-%d %H:%M:%S")


_TOKEN_RE = re.compile(r"[A-Za-z']+")


def _tokens(text: str) -> List[str]:
    return [t.lower() for t in _TOKEN_RE.findall(str(text))]


def _jaccard(a: List[str], b: List[str]) -> float:
    sa, sb = set(a), set(b)
    if not sa or not sb:
        return 0.0
    return float(len(sa & sb) / len(sa | sb))


def _bootstrap_ci(x: np.ndarray, n_boot: int = 1000,
                  ci_level: float = 0.95, seed: int = 142) -> Tuple[float, float, float]:
    """Returns (mean, ci_lo, ci_hi)."""
    x = np.asarray(x, dtype=np.float64)
    x = x[np.isfinite(x)]
    if x.size == 0:
        return float("nan"), float("nan"), float("nan")
    rng = np.random.default_rng(int(seed))
    boot = np.empty(int(n_boot), dtype=np.float64)
    n = x.size
    for i in range(int(n_boot)):
        idx = rng.integers(0, n, size=n)
        boot[i] = float(np.mean(x[idx]))
    lo = float(np.percentile(boot, (1 - ci_level) / 2 * 100))
    hi = float(np.percentile(boot, (1 + ci_level) / 2 * 100))
    return float(np.mean(x)), lo, hi


class _MeanPoolEmbedder:
    """Drop-in replacement for sentence_transformers.SentenceTransformer.

    Uses transformers.AutoModel directly so the sentence_transformers ->
    transformers.Trainer -> apex.amp import chain is not triggered.  apex on
    the v19-arm64 image is missing the `amp` submodule, which crashes the
    Trainer import; this loader sidesteps the problem entirely.
    """

    def __init__(self, model_id: str, device: str):
        from transformers import AutoTokenizer, AutoModel
        self._tok = AutoTokenizer.from_pretrained(model_id)
        self._model = AutoModel.from_pretrained(model_id).to(device)
        self._model.eval()
        self._device = device

    def encode(
        self,
        texts: List[str],
        batch_size: int = 64,
        convert_to_numpy: bool = True,
        show_progress_bar: bool = False,
        normalize_embeddings: bool = True,
    ) -> np.ndarray:
        import torch
        out: List[np.ndarray] = []
        with torch.no_grad():
            for i in range(0, len(texts), int(batch_size)):
                chunk = texts[i:i + int(batch_size)]
                enc = self._tok(chunk, padding=True, truncation=True,
                                max_length=256, return_tensors="pt").to(self._device)
                hidden = self._model(**enc).last_hidden_state
                mask = enc["attention_mask"].unsqueeze(-1).float()
                pooled = (hidden * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1.0)
                if normalize_embeddings:
                    pooled = torch.nn.functional.normalize(pooled, p=2, dim=1)
                out.append(pooled.cpu().numpy().astype(np.float32))
        return np.concatenate(out, axis=0) if out else np.zeros((0, 1), dtype=np.float32)


def _load_embedder(model_id: str, device: str):
    LOG.info("Loading mean-pool embedder: %s (device=%s)", model_id, device)
    return _MeanPoolEmbedder(model_id, device)


def _embed_mean(embedder, texts: List[str], batch_size: int = 64) -> np.ndarray:
    if not texts:
        return np.zeros((1,), dtype=np.float32)
    vecs = embedder.encode(
        texts, batch_size=int(batch_size), convert_to_numpy=True,
        show_progress_bar=False, normalize_embeddings=True,
    )
    return vecs.mean(axis=0).astype(np.float32)


def _cos(a: np.ndarray, b: np.ndarray) -> float:
    if a.shape != b.shape:
        return float("nan")
    na = float(np.linalg.norm(a)); nb = float(np.linalg.norm(b))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return float(np.dot(a, b) / (na * nb))


def _load_pipe_goemo(model_id: str, device_id: int):
    from transformers import pipeline as hf_pipeline
    from transformers import logging as hf_logging
    hf_logging.set_verbosity_error()
    return hf_pipeline(
        task="text-classification",
        model=model_id, device=int(device_id),
        truncation=True, max_length=256, batch_size=64,
        top_k=None,
        framework="pt",
    )


_POSITIVE = {"admiration", "amusement", "approval", "caring", "desire",
             "excitement", "gratitude", "joy", "love", "optimism", "pride",
             "relief"}
_NEGATIVE = {"anger", "annoyance", "disappointment", "disapproval",
             "disgust", "embarrassment", "fear", "grief", "nervousness",
             "remorse", "sadness"}


def _goemo_polarity(pipe, texts: List[str], chunk: int = 256) -> float:
    """Returns mean polarity in [-1, 1] over texts."""
    if not texts:
        return float("nan")
    pols: List[float] = []
    for i in range(0, len(texts), int(chunk)):
        batch = texts[i:i + int(chunk)]
        try:
            results = pipe(batch)
        except Exception as e:
            LOG.warning("GoEmo pipe failed on chunk %d: %s", i, e)
            continue
        for r in results:
            pos = neg = 0.0
            for entry in r:
                lab = str(entry.get("label", "")).lower()
                sc = float(entry.get("score", 0.0))
                if lab in _POSITIVE:
                    pos += sc
                elif lab in _NEGATIVE:
                    neg += sc
            pols.append(pos - neg)
    return float(np.mean(pols)) if pols else float("nan")


def _find_text_col(df: pd.DataFrame) -> str:
    for c in ("body", "text", "content", "post_text", "reply_text"):
        if c in df.columns:
            return c
    raise KeyError(f"No text column in {list(df.columns)}")


def _find_user_col(df: pd.DataFrame) -> str:
    for c in ("author_user_id", "target_user_id", "user_id"):
        if c in df.columns:
            return c
    raise KeyError(f"No user-id column in {list(df.columns)}")


def evaluate(args: argparse.Namespace) -> None:
    out_dir = Path(args.out_dir); out_dir.mkdir(parents=True, exist_ok=True)

    LOG.info("Loading generated forum: %s", args.gen_parquet)
    gen = pd.read_parquet(args.gen_parquet)
    gen_text = _find_text_col(gen); gen_uid = _find_user_col(gen)
    LOG.info("Loading training corpus: %s", args.train_parquet)
    trn = pd.read_parquet(args.train_parquet,
                           columns=["target_user_id", "text"])
    trn = trn.rename(columns={"target_user_id": "user_id", "text": "text"})

    # Restrict to users that actually appear in the generated forum
    gen_users = sorted(gen[gen_uid].dropna().astype(int).unique().tolist())
    LOG.info("Generated forum users: %d", len(gen_users))
    trn = trn[trn["user_id"].isin(gen_users)].copy()

    # Optional per-user post cap
    cap_gen = int(args.max_gen_per_user)
    cap_trn = int(args.max_train_per_user)

    # Load cohort labels (GoEmo) for per-cohort breakdown
    cohort: Dict[int, str] = {}
    if args.labels_csv and Path(args.labels_csv).exists():
        ldf = pd.read_csv(args.labels_csv)
        if "label" in ldf.columns and "target_user_id" in ldf.columns:
            cohort = {int(r["target_user_id"]): str(r["label"]).strip().lower()
                      for _, r in ldf.iterrows()}
            LOG.info("Loaded %d cohort labels from %s",
                     len(cohort), args.labels_csv)

    # Sentence embedder + GoEmo pipeline
    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"
    embedder = _load_embedder(args.embedder_model, device)
    pipe = _load_pipe_goemo(args.goemo_model,
                             0 if device == "cuda" else -1)

    rows: List[Dict] = []
    n_users = len(gen_users)
    for i, uid in enumerate(gen_users):
        gtxt = gen.loc[gen[gen_uid] == uid, gen_text].astype(str).tolist()
        ttxt = trn.loc[trn["user_id"] == uid, "text"].astype(str).tolist()
        if cap_gen > 0 and len(gtxt) > cap_gen:
            gtxt = gtxt[:cap_gen]
        if cap_trn > 0 and len(ttxt) > cap_trn:
            ttxt = ttxt[:cap_trn]
        if not gtxt or not ttxt:
            continue

        ge = _embed_mean(embedder, gtxt, batch_size=int(args.embed_batch_size))
        te = _embed_mean(embedder, ttxt, batch_size=int(args.embed_batch_size))
        cos = _cos(ge, te)

        gp = _goemo_polarity(pipe, gtxt, chunk=int(args.goemo_chunk))
        tp = _goemo_polarity(pipe, ttxt, chunk=int(args.goemo_chunk))
        sent_mae = (abs(gp - tp) if (np.isfinite(gp) and np.isfinite(tp))
                    else float("nan"))

        gtoks = sum((_tokens(t) for t in gtxt), [])
        ttoks = sum((_tokens(t) for t in ttxt), [])
        jacc = _jaccard(gtoks, ttoks)

        rows.append({
            "target_user_id": int(uid),
            "cohort": cohort.get(int(uid), ""),
            "n_gen_posts": len(gtxt),
            "n_train_posts": len(ttxt),
            "style_cosine": float(cos),
            "gen_polarity": float(gp),
            "train_polarity": float(tp),
            "sent_mae": float(sent_mae),
            "lex_jaccard": float(jacc),
        })

        if (i + 1) % 50 == 0 or (i + 1) == n_users:
            LOG.info("Scored %d / %d users", i + 1, n_users)

    if not rows:
        raise RuntimeError("No users scored; check that gen_parquet and "
                           "train_parquet share author_user_id values.")

    df = pd.DataFrame(rows)
    df.to_csv(out_dir / "per_user_reconstruction.csv", index=False)
    LOG.info("Wrote per-user CSV (%d rows)", len(df))

    def _summarize(sub: pd.DataFrame) -> Dict:
        if len(sub) == 0:
            return {"n": 0}
        c_mean, c_lo, c_hi = _bootstrap_ci(sub["style_cosine"].values,
                                            n_boot=int(args.n_boot),
                                            seed=int(args.seed))
        m_mean, m_lo, m_hi = _bootstrap_ci(sub["sent_mae"].values,
                                            n_boot=int(args.n_boot),
                                            seed=int(args.seed))
        j_mean, j_lo, j_hi = _bootstrap_ci(sub["lex_jaccard"].values,
                                            n_boot=int(args.n_boot),
                                            seed=int(args.seed))
        return {
            "n": int(len(sub)),
            "style_cosine_mean": c_mean, "style_cosine_ci_lo": c_lo,
            "style_cosine_ci_hi": c_hi,
            "sent_mae_mean": m_mean, "sent_mae_ci_lo": m_lo,
            "sent_mae_ci_hi": m_hi,
            "lex_jaccard_mean": j_mean, "lex_jaccard_ci_lo": j_lo,
            "lex_jaccard_ci_hi": j_hi,
        }

    summary = {
        "schema": "reconstruction_v1",
        "gen_parquet": str(args.gen_parquet),
        "train_parquet": str(args.train_parquet),
        "labels_csv": str(args.labels_csv) if args.labels_csv else "",
        "embedder_model": args.embedder_model,
        "goemo_model": args.goemo_model,
        "n_users_scored": int(len(df)),
        "global": _summarize(df),
        "per_cohort": {c: _summarize(df[df["cohort"] == c])
                       for c in sorted(df["cohort"].dropna().unique())
                       if c},
    }
    (out_dir / "reconstruction_summary.json").write_text(
        json.dumps(summary, indent=2, default=str), encoding="utf-8")
    LOG.info("Wrote summary | global style_cos=%.3f sent_mae=%.3f",
             summary["global"].get("style_cosine_mean", float("nan")),
             summary["global"].get("sent_mae_mean", float("nan")))

    # Plot
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(7, 6))
        for c, color in zip(sorted(df["cohort"].dropna().unique()),
                             ("C0", "C1", "C2", "C3")):
            sub = df[df["cohort"] == c]
            if len(sub) == 0:
                continue
            ax.scatter(sub["style_cosine"], sub["sent_mae"],
                        s=10, alpha=0.5, label=str(c), color=color)
        ax.set_xlabel("Per-user style embedding cosine (gen vs train)")
        ax.set_ylabel("Per-user GoEmo polarity MAE (gen vs train)")
        ax.set_title("Per-user reconstruction fidelity")
        ax.axhline(0.0, color="gray", linestyle=":", alpha=0.5)
        ax.legend(loc="best")
        fig.tight_layout()
        fig.savefig(out_dir / "reconstruction_plot.png", dpi=140)
        plt.close(fig)
    except Exception as e:
        LOG.warning("Plot failed: %s", e)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Per-user reconstruction fidelity")
    p.add_argument("--gen_parquet", type=str, required=True,
                   help="Phase 2c real-user-reconstructed forum.parquet")
    p.add_argument("--train_parquet", type=str, required=True,
                   help="Per-user training-corpus parquet "
                        "(target_user_id + text columns).")
    p.add_argument("--out_dir", type=str, required=True)
    p.add_argument("--labels_csv", type=str, default="",
                   help="Optional GoEmo cohort labels for per-cohort summary.")
    p.add_argument("--embedder_model", type=str,
                   default="sentence-transformers/all-MiniLM-L6-v2")
    p.add_argument("--goemo_model", type=str,
                   default="SamLowe/roberta-base-go_emotions")
    p.add_argument("--max_gen_per_user", type=int, default=0,
                   help="Cap generated posts per user (0 = no cap).")
    p.add_argument("--max_train_per_user", type=int, default=200,
                   help="Cap training posts per user (default 200).")
    p.add_argument("--embed_batch_size", type=int, default=64)
    p.add_argument("--goemo_chunk", type=int, default=256)
    p.add_argument("--n_boot", type=int, default=1000)
    p.add_argument("--seed", type=int, default=142)
    return p.parse_args()


def main() -> None:
    evaluate(parse_args())


if __name__ == "__main__":
    main()
